platform: linux
image_resource:
  type: docker-image
  source: { repository: alpine }
inputs:
  - name: linux
    optional: true
  - name: windows
    optional: true
  - name: darwin
    optional: true
outputs:
  - name: collected
run:
  path: ash
  args:
    - -c
    - |
      set -euo pipefail
      for platform in linux windows darwin; do
        cp --update "$platform"/* collected
      done
