platform: linux
image_resource:
  type: docker-image
  source: { repository: uhligit/xz }
inputs: [ name: binaries ]
params:
  target:
  prefix:
outputs: [ name: compressed ]
run:
  dir: binaries
  path: ash
  args:
    - -c
    - |
      set -euo pipefail
      [ -z "$prefix" ] && echo "Error: prefix must not be empty" && exit 1
      tar --verbose --create --xz --file=../compressed/"$prefix"-"$target".tar.xz *
