---
platform: linux

image_resource:
  type: docker-image
  source: { repository: rust }

inputs:
  - name: source

caches: # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
  - path: .cargo/bin/
  - path: .cargo/registry/index/
  - path: .cargo/registry/cache/
  - path: .cargo/git/db/
  - path: source/target

run:
  dir: source
  path: bash
  args:
    - -c
    - |
      export CARGO_HOME=$(readlink -f ../.cargo)
      rustup component add rustfmt # TODO Create an image that already has the latest rustfmt
      cargo fmt --check
