---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: uhligit/ansible
    tag: 2.0.0-6-g06fc345

inputs:
  - name: release
  - name: playbook

params:
  INVENTORY:
  VAULT_PASSWORD:
  SSH_KEY:
  EXTRA_VARS: # e.g. service_binary=release/plaintweet

run:
  path: sh
  args:
  - -c
  - |
    ansible-galaxy install --role-file playbook/requirements.yml

    mkdir ~/.ssh
    echo "$SSH_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H "$INVENTORY" >> ~/.ssh/known_hosts

    echo "$VAULT_PASSWORD" > .vault_password
    ansible-playbook \
      playbook/playbook.yml \
      --inventory "$INVENTORY," \
      --extra-vars "$EXTRA_VARS" \
      --vault-password-file .vault_password
