---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: uhligit/ansible

inputs:
  - name: release
  - name: playbook

params:
  INVENTORY:
  VAULT_PASSWORD:
  SSH_KEY:
  EXTRA_VARS: # e.g. service_binary=release/plaintweet
  REQUIREMENTS_YAML_PATH: playbook/requirements.yml
  PLAYBOOK_YAML_PATH: playbook/playbook.yml

run:
  path: sh
  args:
  - -c
  - |
    ansible-galaxy install --role-file "$REQUIREMENTS_YAML_PATH"

    mkdir ~/.ssh
    echo "$SSH_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -H "$INVENTORY" >> ~/.ssh/known_hosts

    echo "$VAULT_PASSWORD" > .vault_password
    ansible-playbook \
      "$PLAYBOOK_YAML_PATH" \
      --inventory "$INVENTORY," \
      --extra-vars "$EXTRA_VARS" \
      --vault-password-file .vault_password
