---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: uhligit/ansible

inputs:
  - name: release
  - name: playbook
  - name: lib

params:
  INVENTORY: # hostname or name of YAML file
  VAULT_PASSWORD:
  SSH_KEY:
  EXTRA_VARS: # e.g. service_binary=release/plaintweet
  PLAYBOOK_PATH: playbook

run:
  path: lib/tasks/ansible/deploy.zsh
