#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_PATH=$(dirname "$(realpath "$0")")

fly \
  set-pipeline \
  --target "$CONCOURSE_TARGET" \
  --pipeline=task-library \
  --yaml-var=secrets="$SECRETS" \
  --var ci-branch="$GIT_BRANCH" \
  --config "$SCRIPT_PATH"/pipelines/pipeline.yml \
