#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_PATH=$(dirname "$(realpath "$0")")

set +u
if [ -z "$GIT_BRANCH" ]; then
  GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi
set -u

fly \
  set-pipeline \
  --target "$CONCOURSE_TARGET" \
  --pipeline=task-library \
  --yaml-var=secrets="$SECRETS" \
  --var ci-branch="$GIT_BRANCH" \
  --config "$SCRIPT_PATH"/pipelines/pipeline.yml \
