platform: linux
image_resource:
  type: docker-image
  source: { repository: alpine }
inputs:
  - name: source
  - name: ssh-config
params:
  source: source/
  target:
run:
  path: sh
  args:
  - -c
  - |
    set -eu
    apk add rsync openssh yq zsh # TODO separate image

    rsync \
        --progress \
        --recursive \
        --rsh 'ssh -o UserKnownHostsFile=ssh-config/known_hosts -o IdentityFile=ssh-config/id' \
      "${source:?not set}" \
      "${target:?not set}"
