---
platform: linux

image_resource:
  type: docker-image
  source: { repository: suhlig/webservices-ci }

inputs:
  - name: source

params:
  tarball:

outputs:
  - name: target

run:
  path: sh
  args:
  - -exc
  - |
    tar cvfz "target/${tarball:?not set}" -C source .
