---
platform: linux

image_resource:
  type: docker-image
  source: { repository: busybox }

inputs:
  - name: release

outputs:
  - name: extracted

params:
  tarball:

run:
  path: sh
  args:
  - -exc
  - |
    tar xvfz release/${tarball:?not set} -C extracted
