platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

inputs:
  - name: source
  - name: base-image # https://github.com/concourse/oci-build-task/pull/52#issuecomment-892907161
    optional: true

params:
  CONTEXT: source
  UNPACK_ROOTFS: true
  BUILD_ARG_VERSION:

caches:
  - path: cache

outputs:
  - name: image

run:
  path: build
