---
platform: linux

image_resource:
  type: docker-image
  source: { repository: bats/bats }

inputs:
  - name: release-content
  - name: source
  - name: bats-assert
  - name: bats-support

params:
  TERM: linux
  TEST_DIR: source/test
  PROGRAM_UNDER_TEST:

run:
  path: bash
  args:
    - -c
    - |
      bats --print-output-on-failure "$TEST_DIR"
