platform: linux
image_resource:
  type: docker-image
  source: { repository: alpine }
inputs:
  - name: ssh-config
    optional: true
params: { SSH_KEY: }
outputs: [ name: ssh-config ]
run:
  path: ash
  args:
    - -c
    - |
      set -euo pipefail
      IFS=$'\n\t'

      echo "${SSH_KEY:?not set}" > ssh-config/id
      chmod 600 ssh-config/id
