jobs:
  - name: build-image
    plan:
      - in_parallel:
        - get: image-source
          trigger: true
        - get: lib
      - task: build-image
        privileged: true
        file: lib/tasks/oci/build-image.yml
        input_mapping: { source: image-source }
        params:
          CONTEXT: image-source/images/ansible
        output_mapping: { image: image }
      - load_var: image-version
        file: image-source/.git/describe_ref # populated by the git-resource
      - put: image
        params:
          image: image/image.tar
          version: ((.:image-version))
          bump_aliases: true

resources:
  - name: image-source
    type: git
    icon: github-circle
    source: &github
      uri: git@github.com:suhlig/concourse-task-store.git
      branch: add-ansible
      private_key: ((github.ssh_key))
      paths: [ images/ansible/Dockerfile ]

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: uhligit/ansible
      username: suhlig
      password: ((dockerhub.authtoken))

  - name: task-store
    type: git
    icon: file-tree
    source:
      uri: git@github.com:suhlig/concourse-task-store.git
      private_key: ((github.ssh_key))
