jobs:
  - name: build-ansible-image
    plan:
      - in_parallel:
        - get: image-source
          trigger: true
        - get: lib
      - task: build-image
        privileged: true
        file: lib/tasks/oci/build-image.yml
        input_mapping: { source: image-source }
        params:
          CONTEXT: source/images/ansible
        output_mapping: { image: image }
      - load_var: image-version
        file: image-source/.git/describe_ref # populated by the git-resource
      - put: image
        params:
          image: image/image.tar
          version: ((.:image-version))
          bump_aliases: true

resources:
  - name: lib
    type: git
    icon: file-tree
    source: &github
      uri: git@github.com:suhlig/concourse-task-library.git
      branch: add-ansible
      private_key: ((secrets.github.ssh_key))

  - name: image-source
    type: git
    icon: github-circle
    source:
      <<: *github
      paths: [ images/ansible/Dockerfile ]
      fetch_tags: true

  - name: image
    type: registry-image
    icon: docker
    source:
      repository: uhligit/ansible
      username: suhlig
      password: ((secrets.dockerhub.authtoken))
