jobs:
  - name: build-ansible-image
    plan:
      - in_parallel:
        - get: ansible-image-source
          trigger: true
        - get: ansible-pypi-package
          trigger: true
        - get: lib
      - load_var: package-info
        file: ansible-pypi-package/info.json
      - task: build-image
        privileged: true
        file: lib/tasks/oci/build-image.yml
        input_mapping: { source: ansible-image-source }
        params:
          CONTEXT: source/images/ansible
          BUILD_ARG_VERSION: ((.:package-info.version))
        output_mapping: { image: image }
      - load_var: image-version
        file: ansible-image-source/.git/describe_ref # populated by the git-resource
      - put: ansible-image
        params:
          image: image/image.tar
          version: ((.:image-version))
          bump_aliases: true

resources:
  - name: lib
    type: git
    icon: file-tree
    source: &github
      branch: pypi-resource
      uri: git@github.com:suhlig/concourse-task-library.git
      private_key: ((secrets.github.ssh_key))

  - name: ansible-image-source
    type: git
    icon: github-circle
    source:
      <<: *github
      paths: [ images/ansible/Dockerfile ]
      fetch_tags: true

  - name: ansible-image
    type: registry-image
    icon: docker
    source:
      repository: uhligit/ansible
      username: suhlig
      password: ((secrets.dockerhub.authtoken))

  - name: ansible-pypi-package
    type: pypi
    source:
      package: ansible

resource_types:
  - name: pypi
    type: registry-image
    source:
      repository: uhligit/concourse-pypi-resource
      tag: latest
