platform: linux
image_resource:
  type: docker-image
  source:
    repository: uhligit/ansible
inputs:
  - name: lib
  - name: playbook
  - name: ssh-config
    optional: true
params:
  INVENTORY: # hostname or name of YAML file
  VAULT_PASSWORD:
  PLAYBOOK_PATH: playbook # where to find {playbook,inventory,requirements}.yml and ansible.cfg
  SSH_KEY:
  EXTRA_VARS: {} # e.g. service_binary=release/plaintweet
outputs: [ name: ssh-config ]
run: { path: lib/tasks/ansible/ssh-known-hosts/task.zsh }
