platform: linux
image_resource:
  type: docker-image
  source: { repository: uhligit/httpspell }
inputs:
  - name: lib
  - name: dictionary
    optional: true
  - name: ignorewords
    optional: true
  - name: site
    optional: true
params:
  APP_URL:
  verbose: false
  ignorewordsfile:
run:
  path: zsh
  args:
    - -c
    - |
      set -euo pipefail

      if [ -d site ]; then
        caddy start --config lib/tasks/httpspell/Caddyfile
        trap "caddy stop" EXIT
        APP_URL=http://localhost:2015
      fi

      optionalArguments=()

      if [ -d dictionary ]; then
        optionalArguments+=("--personal-dictionary=dictionary/*.dic")
      fi

      if [ -d ignorewords ] && [ ! -z $ignorewordsfile ] ; then
        optionalArguments+=("--ignore=ignorewords/$ignorewordsfile")
      fi

      if [ "$verbose" = true ]; then
        optionalArguments+=("--verbose")
      fi

      httpspell "${optionalArguments[@]}" "${APP_URL:?Missing}"
