---
platform: linux

image_resource:
  type: docker-image
  source: { repository: goreleaser/goreleaser }

inputs:
  - name: source

params:
  GITHUB_TOKEN:

outputs:
  - name: dist

run:
  path: bash
  dir: source
  args:
  - -c
  - |
    goreleaser release
    cp -R dist/. ../dist/
