---
platform: linux

image_resource:
  type: registry-image
  source: { repository: goreleaser/goreleaser }

inputs:
  - name: source

params:
  BINARY:

outputs:
  - name: snapshot

run:
  path: bash
  dir: source
  args:
  - -c
  - |
    goreleaser build --snapshot --single-target --output ../snapshot/"$BINARY"
